name: Update TAC data from LFX
description: Action that syncs data from LFX into the TAC website
inputs:
  landscape_url:
    description: "URL for the project's landscape"
    default: ""
  artwork_url:
    description: "URL for the project's artwork repo"
    default: ""
  lfx_tac_committee_url:
    description: "URL to the committee in LFX"
    default: ""
  tac_agenda_gh_project_url:
    description: "URL for the GitHub Project in the TAC repo for managing TAC meeting agendas"
    default: ""
runs:
  using: composite
  steps:
  - name: Harden Runner
    uses: step-security/harden-runner@4d991eb9b905ef189e4c376166672c3f2f230481 # v2.11.0
    with:
      egress-policy: audit
  - name: Check out repo
    uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
    with:
      token: ${{ env.token }}
      repository: ${{ env.repository }}
      ref: ${{ env.ref }}
      path: tac-repo
  - name: Checkout lfx-tac-actions
    uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.1.7@v4
    with:
      token: ${{ env.token }}
      repository: jmertic/lfx-tac-actions
      path: lfx-tac-actions
  - name: Set up Python 3.x
    uses: actions/setup-python@42375524e23c412d93fb67b49958b491fce71c38 # v5.4.0
    with:
      python-version: '3.x'
  - name: Install poetry
    uses: abatilo/actions-poetry@3765cf608f2d4a72178a9fc5b918668e542b89b1 # v4.0.0
  - name: Install dependencies
    shell: bash
    working-directory: ./lfx-tac-actions
    run: |
      poetry install
  - name: Run build
    working-directory: ./lfx-tac-actions
    shell: bash
    env:
      LANDSCAPE_URL: ${{ inputs.landscape_url }}
      ARTWORK_URL: ${{ inputs.artwork_url }}
      LFX_TAC_COMMITTEE_URL: ${{ inputs.lfx_tac_committee_url }}
      TAC_AGENDA_GH_PROJECT_URL: ${{ inputs.tac_agenda_gh_project_url }}
      GH_TOKEN: ${{ env.token }}
      GITHUB_TOKEN: ${{ env.token }}
    run: |
      poetry run updateprojects -o ../tac-repo/_data/projects.csv
      poetry run updatetacmembers -o ../tac-repo/_data/tacmembers.csv
      poetry run updatetacagendaitems -o ../tac-repo/_data/meeting-agenda-items.csv
      poetry run updateclomonitor -o ../tac-repo/_data/clomonitor.yaml
  - name: Get current date
    id: date
    uses: Kaven-Universe/github-action-current-date-time@f2c12d90cff9c3e7b1f50430886e632fe31fcee1 # v1.4.0
    with:
      format: "YYYY-MM-DD"
  - name: Create Pull Request
    uses: peter-evans/create-pull-request@dd2324fc52d5d43c699a5636bcf19fceaa70c284 # v7.0.7
    with:
      token: ${{ env.token }}
      branch-suffix: timestamp
      path: ./tac-repo
      title: "Update Data Sources from LFX ${{ steps.date.outputs.time }}"
      labels: automerge
      commit-message: Update Data Sources from LFX
      signoff: true

