name: Update TAC data from LFX
description: Action that syncs data from LFX into the TAC website
inputs:
  landscape_url:
    description: "URL for the project's landscape"
    required: false
    default: ""
  slug:
    description: "Project slug as defined in LFX PCC"
    required: false
    default: ""
  lfx_tac_committee_url:
    description: "URL to the committee in LFX"
    required: false
    default: ""
  tac_agenda_gh_project_url:
    description: "URL for the GitHub Project in the TAC repo for managing TAC meeting agendas"
    required: false
    default: ""
  overview_decks:
    description: "JSON array of Google Presentations to export ( format is '[{'url': GOOGLE-DRIVE-URL,'filename': EXPORT_FILENAME},...]' )"
    required: false
    default: ""
  updateprojects:
    description: "Run updateprojects"
    required: false
    default: 'true'
  updatetacmembers:
    description: "Run updatetacmembers"
    required: false
    default: 'true'
  updatetacagendaitems:
    description: "Run updatetacagendaitems"
    required: false
    default: 'true'
  updateclomonitor:
    description: "Run updateclomonitor"
    required: false
    default: 'false'
  updatecharters:
    description: "Run updatecharters"
    required: false
    default: 'false'
  updatedecks:
    description: "Run updatedecks"
    required: false
    default: 'false'
runs:
  using: composite
  steps:
  - name: Harden Runner
    uses: step-security/harden-runner@5ef0c079ce82195b2a36a210272d6b661572d83e # v2.14.2
    with:
      egress-policy: audit
  - name: Check out repo
    uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
    with:
      token: ${{ env.token }}
      repository: ${{ env.repository }}
      ref: ${{ env.ref }}
      path: repo
  - name: Checkout lfx-tac-actions
    uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v4.1.7@v4
    with:
      token: ${{ env.token }}
      repository: jmertic/lfx-tac-actions
      path: lfx-tac-actions
  - name: Set up Python 3.x
    uses: actions/setup-python@a309ff8b426b58ec0e2a45f0f869d46889d02405 # v6.2.0
    with:
      python-version: '3.x'
  - name: Install poetry
    uses: abatilo/actions-poetry@3765cf608f2d4a72178a9fc5b918668e542b89b1 # v4.0.0
  - name: Install dependencies
    shell: bash
    working-directory: ./lfx-tac-actions
    run: |
      poetry install
  - name: Run updateprojects
    working-directory: ./lfx-tac-actions
    shell: bash
    if: inputs.updateprojects == 'true' && inputs.landscape_url != ''
    run: |
      poetry run updateprojects -o ../repo/_data/projects.csv --landscape_url ${{ inputs.landscape_url }}
  - name: Run updatetacmembers
    working-directory: ./lfx-tac-actions
    shell: bash
    if: inputs.updatetacmembers == 'true' && inputs.lfx_tac_committee_url != ''
    run: |
      poetry run updatetacmembers -o ../repo/_data/tacmembers.csv --lfx_tac_committee_url ${{ inputs.lfx_tac_committee_url }}
  - name: Run updatetacagendaitems
    working-directory: ./lfx-tac-actions
    shell: bash
    if: inputs.updatetacagendaitems == 'true' && inputs.tac_agenda_gh_project_url != ''
    env:
      GH_TOKEN: ${{ env.token }}
    run: |
      poetry run updatetacagendaitems -o ../repo/_data/meeting-agenda-items.csv --tac_agenda_gh_project_url ${{ inputs.tac_agenda_gh_project_url }}
  - name: Run updateclomonitor
    working-directory: ./lfx-tac-actions
    shell: bash
    if: inputs.updateclomonitor == 'true' && inputs.landscape_url != ''
    run: |
      poetry run updateclomonitor -o ../repo/_data/meeting-agenda-items.csv --landscape_url ${{ inputs.landscape_url }}
  - name: Run updatecharters
    working-directory: ./lfx-tac-actions
    shell: bash
    if: inputs.updatecharters == 'true' && inputs.slug != ''
    run: |
      poetry run updatecharters -o ../repo/project_charters --slug ${{ inputs.slug }}
  - name: Run updatedecks
    working-directory: ./lfx-tac-actions
    shell: bash
    if: inputs.updatedecks == 'true' && inputs.overview_decks != ''
    run: |
      poetry run updatedecks -o ../repo/overview_deck --overview_decks '${{ inputs.overview_decks }}'
  - name: Get current date
    id: date
    uses: Kaven-Universe/github-action-current-date-time@f2c12d90cff9c3e7b1f50430886e632fe31fcee1 # v1.4.0
    with:
      format: "YYYY-MM-DD"
  - name: Create Pull Request
    id: cpr
    uses: peter-evans/create-pull-request@c0f553fe549906ede9cf27b5156039d195d2ece0 # v8.1.0
    with:
      token: ${{ env.token }}
      branch-suffix: timestamp
      path: ./repo
      title: "Update Data Sources from LFX ${{ steps.date.outputs.time }}"
      labels: automerge
      commit-message: Update Data Sources from LFX
      signoff: true
      delete-branch: true
  - name: Enable Pull Request Automerge
    if: steps.cpr.outputs.pull-request-number != ''
    working-directory: ./repo
    shell: bash
    run: |
      gh pr merge --squash --auto "${{ steps.cpr.outputs.pull-request-number }}" \
      || gh pr merge --squash "${{ steps.cpr.outputs.pull-request-number }}"
    env:
      GH_TOKEN: ${{ env.token }}
